sudo: false
language: ruby
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

before_install:
  - gem install bundler -v 2.2.28
  - yarn --ignore-engines
  - bundle config gems.contribsys.com ${SIDEKIQ_CREDS}

script:
  - bundle exec rake test
  - bundle exec bundle audit check --update
  - bundle exec brakeman -A -z --ensure-latest --no-pager
  - bundle exec standardrb
  - yarn audit
