sudo: false
language: ruby
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

script:
  - bundle exec rake test
  - bundle exec bundle audit check --update
  - bundle exec brakeman -A -z --ensure-latest --no-pager
  - bundle exec standardrb
