version: '3'
services:
  rails-infrastructure-canary-staging-app:
    image: 056154071827.dkr.ecr.us-east-1.amazonaws.com/rails-infrastructure-canary:latest
    # command: server
    ports:
      - "0:80" # dynamic ports not supported on Fargate
    # encrypted secrets from AWS SSM Parameter Store
    env_file:
      - $CLUSTER.env
    # unecrypted env vars
    # environment:
    restart: always
