development: &dev
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

test:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] || '8e1e69e93af02213eaafc6fa1ba5ac88bbedb8e8d8856e2419bdbf5ed5d0c0cd779fe21ef912d74c374b3ce2b5c7a1e9b54bb5ad570036a3ab8a162488912431' %>

staging:
  <<: *dev

production:
  <<: *dev
