name: Build & Deploy ECS

on:
  push:
    branches:
      - test-build
  workflow_dispatch:
    inputs:
      auto-deploy:
        type: boolean
        description: Deploy image after building?
        required: true
        default: 'false'

jobs:
  build:
    name: Build
    uses: CruGlobal/.github/.github/workflows/build-ecs.yml@fix-build-number
    with:
      workflow-ref: fix-build-number